"""ERCOT Fuel Mix Report → ``ercot_fuel_mix_15min``: energy generated by fuel in every 15-minute settlement
interval, 2007 → today.

Inputs: one workbook per year (``IntGenbyFuel<year>.xlsx``) and the 2007-2024 zip of older ones (``.xls``
up to 2015). Each month sheet is a wide table, one row per operating day and fuel and one column per
interval. The layout changed many times, so columns are found by what their header says:

- day and fuel: ``Date`` + ``Fuel`` / ``Fuel Type`` (2011, 2017+) or one cell such as ``11/04/07 - Coal``,
  ``11/01/09-Coal`` or ``11/04/12_Biomass`` under ``Date - Fuel`` / ``DateFuel`` / ``Date-Fuel``;
- ``Settlement Type`` (FINAL / INITIAL, 2017+; values are replaced by final settlement about two months
  later, per the workbook notes);
- 96 interval columns labelled by interval ending (``0:15`` ... ``0:00`` = 24:00), as text, Excel times or
  day fractions; ``Total`` / ``Daily MWH`` and unlabelled columns are ignored.

**Unit:** MWh per 15-minute interval, as published (``generation_mwh``): each month's sum per fuel equals
the workbook's "Energy, GWh" Summary sheet, and the daily ``Total`` column is the sum of the row's
intervals. ``WSL`` (Wholesale Storage Load, per the Summary notes) is negative: storage charging.

**Daylight saving time.** The spring-forward day has 92 intervals and the fall-back day 100. ERCOT wrote
the day's values in time order and left the leftover columns empty (null or 0 for every fuel); where
that block sits depends on the vintage:

- spring: the 4 empty columns are 02:15-03:00 (2008, 2011, 2012, 2017+), 02:00-02:45 (2009, 2013, 2016),
  01:00-01:45 (2007) or 23:15-24:00 (2010, 2014, 2015). The block is dropped and the 92 remaining values
  are assigned in order to the day's 92 real intervals.
- fall: the repeated hour is either inserted after 02:00 with time labels (2009), or placed in extra
  columns: ``DST1``-``DST4`` after 24:00 (2010-2012, 2015, 2016; a continuity check shows they hold the
  day's last 4 intervals, i.e. the 100 values run in order) or ``01:15 (DST)`` ... ``02:00 (DST)`` (2017+,
  the repeated hour itself). Slots are put in time order and the 100 values assigned in order. In 2007,
  2008, 2013 and 2014 the repeated hour was not published (the daily total still counts it in 2007, 2008
  and 2014): those days have 96 intervals and hour ending 02:00 is taken as its first pass.

``published_label`` keeps the column header the value came from, so a re-aligned value shows it.
On other days the extra DST columns hold placeholders (0 or empty) and are ignored; a non-zero value
there raises.

**Fuels** (``fuel`` normalized, ``fuel_label`` as published): biomass, coal, gas (gas other than combined
cycle: "Gas" from Dec 2008 on and "Gas_GT"), gas_cc ("Gas_CC", "Gas-CC"), gas_total ("Gas" in a month
sheet with no combined-cycle row: 2007 to Nov 2008), hydro, nuclear, other ("Oth", "Other": petroleum coke, fuel oil,
other or unknown fuels per the Summary notes), solar ("Sun", "Solar"), wind ("Wnd", "Wind") and wsl.
In Nov 2011 an all-zero "Solar" row duplicates "Sun" on 8 days; an all-zero row that duplicates another
row's fuel on the same day is dropped.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass

import fastexcel
import polars as pl

from basecast_pipelines.parsers.ercot._market_common import dst_days, sort_unique, to_utc, workbooks
from basecast_pipelines.processing.core import Dataset, RawFile, latest_by
from basecast_pipelines.processing.tabular import clean_label, excel_date, num, snake

log = logging.getLogger(__name__)

SOURCE_ID = "ercot_fuel_mix"

FUELS = {
    "biomass": "biomass",
    "coal": "coal",
    "gas": "gas",
    "gas_gt": "gas",
    "gas_cc": "gas_cc",
    "hydro": "hydro",
    "nuclear": "nuclear",
    "oth": "other",
    "other": "other",
    "sun": "solar",
    "solar": "solar",
    "wnd": "wind",
    "wind": "wind",
    "wsl": "wsl",
}

_ENDS = tuple(range(15, 1441, 15))  # interval endings, minutes after local midnight
_SKIPPED = frozenset(range(135, 181, 15))  # 02:15-03:00, absent on spring-forward days
_MONTH_SHEET = re.compile(r"^(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)", re.IGNORECASE)
_TIME = re.compile(r"^(?:\d{4}-\d\d-\d\d\s+)?(\d{1,2}):(\d\d)(?::\d\d(?:\.\d+)?)?$")
_OVERFLOW = re.compile(r"^dst\s*([1-4])$", re.IGNORECASE)
_DST_MARK = re.compile(r"\(?\s*dst\s*\)?", re.IGNORECASE)
_DATE_FUEL = r"^\s*(\d{1,2}/\d{1,2}/\d{2,4})\s*[-_ ]\s*(.+?)\s*$"
# Low-cardinality text, kept as Categorical to hold the ~5.4M rows of the 2007-2024 zip in half the
# memory; Parquet stores them as plain strings (BigQuery STRING).
_LABELS = ["interval_ending", "fuel", "fuel_label", "settlement_type", "published_label"]


@dataclass(frozen=True)
class _Slot:
    col: str  # grid column
    label: str  # header as published (Excel times as HH:MM)
    end: int | None  # interval ending in minutes (15..1440); None for DST1-DST4
    kind: str  # "regular" | "repeated" (time-labelled repeated hour) | "overflow" (DST1-DST4)
    order: float  # position in time on a fall-back day


def _minutes(text: str) -> int | None:
    """Header text → minutes after midnight for a time label (``0:15``, ``1899-12-31 00:15:00``, ``0.0104``)."""
    m = _TIME.match(text)
    if m:
        minutes = int(m.group(1)) * 60 + int(m.group(2))
    else:
        try:
            fraction = float(text)
        except ValueError:
            return None
        if not 0 <= fraction < 1:
            return None
        minutes = round(fraction * 1440)
    return minutes if minutes % 15 == 0 and 0 <= minutes <= 1440 else None


def _repeated_order(end: int) -> float:
    return 120 + (end - 60) / 100  # after the first pass of hour ending 02:00, before 02:15


def _slots(header: list[object], columns: list[str], where: str) -> list[_Slot]:
    """Interval columns in sheet order. Plain time columns are taken by position (96, or 100 when the
    repeated hour sits inline after 02:00): one 2009 sheet repeats a label and shifts the rest by one."""
    timed: list[tuple[str, str, int]] = []
    extra: list[_Slot] = []
    for col, raw in zip(columns, header):
        text = clean_label(raw) if raw is not None else ""
        if not text:
            continue
        if m := _OVERFLOW.match(text):
            extra.append(_Slot(col, text, None, "overflow", 1440 + int(m.group(1))))
            continue
        marked = bool(_DST_MARK.search(text))
        minutes = _minutes(_DST_MARK.sub("", text).strip())
        if minutes is None:
            continue
        end = minutes or 1440
        if marked:  # "01:15 (DST)": the repeated hour, labelled by time
            if not 75 <= end <= 120:
                raise ValueError(f"{where}: repeated-hour column {text!r} outside hour ending 02:00")
            extra.append(_Slot(col, text, end, "repeated", _repeated_order(end)))
        else:
            timed.append((col, f"{minutes // 60:02d}:{minutes % 60:02d}", end))
    if len(timed) == 96:
        expected = [(e, "regular") for e in _ENDS]
    elif len(timed) == 100:
        expected = (
            [(e, "regular") for e in _ENDS if e <= 120]
            + [(e, "repeated") for e in range(75, 121, 15)]
            + [(e, "regular") for e in _ENDS if e > 120]
        )
    else:
        raise ValueError(f"{where}: {len(timed)} interval columns, expected 96 (00:15-24:00)")
    off = [label for (_, label, end), (want, _) in zip(timed, expected) if end != want]
    if off and len(timed) == 100:
        raise ValueError(f"{where}: inline repeated hour with unexpected labels, e.g. {off[0]}")
    if off:
        log.warning("%s: %d interval headers disagree with their position (first %s); read by position",
                    where, len(off), off[0])
    slots = [
        _Slot(col, label, want, kind, want if kind == "regular" else _repeated_order(want))
        for (col, label, _), (want, kind) in zip(timed, expected)
    ]
    return slots + extra


def _header_row(grid: pl.DataFrame) -> int | None:
    for i, row in enumerate(grid.head(15).iter_rows()):
        cells = [clean_label(c) for c in row if c is not None]
        times = sum(_minutes(c) is not None for c in cells)
        if times >= 90 and any(re.match(r"date", c, re.IGNORECASE) for c in cells):
            return i
    return None


def _day_rows(grid: pl.DataFrame, header_row: int, slots: list[_Slot], where: str) -> pl.DataFrame:
    """One row per (local_date, fuel) with typed slot columns."""
    header = {clean_label(c).lower(): col for col, c in zip(grid.columns, grid.row(header_row)) if c is not None}
    body = grid.slice(header_row + 1)
    combined = next((col for h, col in header.items() if re.fullmatch(r"date\s*-?\s*fuel", h)), None)
    first = combined or header.get("date")
    if first is None:
        raise ValueError(f"{where}: no Date column")
    if combined:
        parts = pl.col(combined).str.extract_groups(_DATE_FUEL)
        date_text, fuel_label = parts.struct.field("1"), parts.struct.field("2")
    else:
        fuel_col = next((col for h, col in header.items() if re.fullmatch(r"fuel( type)?", h)), None)
        if fuel_col is None:
            raise ValueError(f"{where}: no Fuel column")
        date_text, fuel_label = pl.col(first), pl.col(fuel_col).str.strip_chars()
    settlement = next((col for h, col in header.items() if re.fullmatch(r"settlement type", h)), None)
    day = body.select(
        pl.col(first).alias("_first"),
        excel_date(date_text, formats=("%m/%d/%y", "%m/%d/%Y")).alias("local_date"),
        fuel_label.alias("fuel_label"),
        (pl.col(settlement).str.strip_chars().str.to_uppercase() if settlement else pl.lit(None, pl.String))
        .alias("settlement_type"),
        *[num(s.col).alias(s.col) for s in slots],
    )
    unread = day.filter(pl.col("_first").is_not_null() & (pl.col("local_date").is_null() | pl.col("fuel_label").is_null()))
    if unread.height:
        raise ValueError(f"{where}: unreadable date/fuel cell {unread['_first'][0]!r}")
    day = day.filter(pl.col("local_date").is_not_null()).drop("_first")  # footers: no date

    labels = {v: FUELS.get(snake(v), snake(v)) for v in day["fuel_label"].unique().to_list()}
    day = day.with_columns(pl.col("fuel_label").replace_strict(labels, return_dtype=pl.String).alias("fuel"))
    has_cc = (pl.col("fuel") == "gas_cc").any()  # per month sheet: plain "Gas" is all gas before the split
    day = day.with_columns(
        pl.when((pl.col("fuel") == "gas") & ~has_cc).then(pl.lit("gas_total")).otherwise(pl.col("fuel")).alias("fuel")
    )
    regular = [s.col for s in slots if s.kind == "regular"]
    all_zero = pl.all_horizontal([pl.col(c).fill_null(0) == 0 for c in regular])
    day = day.filter(~((pl.len().over("local_date", "fuel") > 1) & all_zero))
    return sort_unique(day, ["local_date", "fuel"], where)


def _dst_day_slots(day: pl.DataFrame, slots: list[_Slot], kind: str, where: str) -> list[tuple[_Slot, int, bool]]:
    """(slot, interval ending, repeated) for one spring-forward or fall-back day: the published values in
    time order, placeholders dropped, assigned in order to the day's real intervals."""
    empty = {
        s.col: day.select((pl.col(s.col).is_null() | (pl.col(s.col) == 0)).all()).item() for s in slots
    }
    ordered = sorted(slots, key=lambda s: s.order)
    if kind == "spring":
        real = [(e, False) for e in _ENDS if e not in _SKIPPED]
        stray = [s.label for s in ordered if s.kind != "regular" and not empty[s.col]]
        if stray:
            raise ValueError(f"{where}: repeated-hour columns {stray} carry data on a spring-forward day")
        regular = [s for s in ordered if s.kind == "regular"]
        blank = [i for i, s in enumerate(regular) if empty[s.col]]
        if len(blank) == 4 and blank[-1] - blank[0] == 3:
            used = [s for i, s in enumerate(regular) if i not in blank]
            return [(s, e, r) for s, (e, r) in zip(used, real, strict=True)]
        log.warning("%s: spring-forward day without a 4-slot placeholder block (%s); using labels", where, blank)
        return [(s, s.end, False) for s in regular if s.end not in _SKIPPED]
    real = (
        [(e, False) for e in _ENDS if e <= 120]
        + [(e, True) for e in range(75, 121, 15)]
        + [(e, False) for e in _ENDS if e > 120]
    )
    used = [s for s in ordered if s.kind == "regular" or not empty[s.col]]
    if len(used) == len(real):
        return [(s, e, r) for s, (e, r) in zip(used, real, strict=True)]
    if all(s.kind == "regular" for s in used):
        log.info("%s: the repeated hour is not published; hour ending 02:00 taken as its first pass", where)
        return [(s, s.end, False) for s in used]
    raise ValueError(f"{where}: fall-back day with {len(used)} usable interval columns")


def _sheet(grid: pl.DataFrame, where: str) -> pl.DataFrame | None:
    header_row = _header_row(grid)
    if header_row is None:
        return None
    slots = _slots(list(grid.row(header_row)), grid.columns, where)
    day = _day_rows(grid, header_row, slots, where)
    if not day.height:
        return None
    index = ["local_date", "fuel", "fuel_label", "settlement_type"]
    slot_frame = pl.DataFrame(
        {"col": [s.col for s in slots], "published_label": [s.label for s in slots]},
        schema={"col": pl.String, "published_label": pl.String},
    )

    special = {}
    for year in day["local_date"].dt.year().unique().to_list():
        spring, fall = dst_days(year)
        special.update({spring: "spring", fall: "fall"})
    special.pop(None, None)
    is_special = pl.col("local_date").is_in(list(special))

    extra = [s.col for s in slots if s.kind != "regular"]
    if extra:
        stray = day.filter(~is_special & pl.any_horizontal([pl.col(c).fill_null(0) != 0 for c in extra]))
        if stray.height:
            raise ValueError(f"{where}: DST columns carry data on {stray['local_date'][0]}, not a DST day")

    maps = [
        pl.DataFrame(
            {"col": [s.col for s in slots if s.kind == "regular"],
             "end": [s.end for s in slots if s.kind == "regular"],
             "dst_flag": [False] * 96},
            schema={"col": pl.String, "end": pl.Int32, "dst_flag": pl.Boolean},
        ).with_columns(pl.lit(None, pl.Date).alias("local_date"))
    ]
    for d, kind in special.items():
        rows = day.filter(pl.col("local_date") == d)
        if not rows.height:
            continue
        assigned = _dst_day_slots(rows, slots, kind, f"{where}:{d}")
        maps.append(
            pl.DataFrame(
                {"col": [s.col for s, _, _ in assigned], "end": [e for _, e, _ in assigned],
                 "dst_flag": [r for _, _, r in assigned]},
                schema={"col": pl.String, "end": pl.Int32, "dst_flag": pl.Boolean},
            ).with_columns(pl.lit(d, pl.Date).alias("local_date"))
        )
    slot_map = pl.concat(maps)

    long = day.unpivot(index=index, on=[s.col for s in slots], variable_name="col", value_name="generation_mwh")
    normal = long.filter(~is_special).join(slot_map.filter(pl.col("local_date").is_null()).drop("local_date"), on="col")
    dst = long.filter(is_special).join(slot_map.filter(pl.col("local_date").is_not_null()), on=["local_date", "col"])
    return (
        pl.concat([normal, dst], how="diagonal")
        .filter(pl.col("generation_mwh").is_not_null())
        .join(slot_frame, on="col", how="left")
        .drop("col")
    )


def _workbook(name: str, data: bytes, where: str) -> pl.DataFrame:
    reader = fastexcel.read_excel(data)
    frames = []
    for sheet in reader.sheet_names:
        if sheet.lower().startswith("chart"):
            continue  # chart sheets hold no cells
        grid = reader.load_sheet(sheet, header_row=None, dtypes="string").to_polars()
        grid = grid.rename({old: f"c{i}" for i, old in enumerate(grid.columns)})
        frame = _sheet(grid, f"{where}:{name}:{sheet}") if grid.height else None
        if frame is None:
            if _MONTH_SHEET.match(sheet) and grid.height > 1 and _header_row(grid) is None:
                raise ValueError(f"{where}:{name}:{sheet}: month sheet without an interval header")
            continue
        frames.append(frame)
    if not frames:
        raise ValueError(f"{where}:{name}: no month sheet with interval data")
    df = pl.concat(frames)
    local = pl.col("local_date").cast(pl.Datetime("us")) + pl.duration(minutes=pl.col("end") - 15)
    start = to_utc(local, pl.col("dst_flag"))
    hh = (pl.col("end") // 60).cast(pl.String).str.zfill(2)
    mm = (pl.col("end") % 60).cast(pl.String).str.zfill(2)
    df = df.select(
        start.alias("interval_start_utc"),
        (start + pl.duration(minutes=15)).alias("interval_end_utc"),
        "local_date",
        pl.concat_str([hh, mm], separator=":").alias("interval_ending"),
        "dst_flag",
        "fuel",
        "fuel_label",
        "settlement_type",
        "generation_mwh",
        "published_label",
    ).with_columns(pl.col(_LABELS).cast(pl.Categorical))
    return sort_unique(df, ["interval_start_utc", "fuel"], f"{where}:{name}")


def parse_fuel_mix(f: RawFile) -> pl.DataFrame | None:
    """One workbook at a time (the 2007-2024 zip holds 18), each finished and sorted on its own, then one
    concat (a single-chunk frame, so the runner's lineage columns do not force another copy). Workbooks
    must not overlap in time."""
    frames = [_workbook(name, data, f.key) for name, data in workbooks(f)]
    if not frames:
        return None  # not a spreadsheet or a zip of spreadsheets
    frames.sort(key=lambda d: d["interval_start_utc"][0])
    for a, b in zip(frames, frames[1:]):
        if b["interval_start_utc"][0] <= a["interval_start_utc"][-1]:
            raise ValueError(f"{f.key}: workbooks overlap in time around {b['interval_start_utc'][0]}")
    return pl.concat(frames)


DATASETS = [
    Dataset(
        name="ercot_fuel_mix_15min",
        target="bigquery",
        mode="by_key",
        description="ERCOT generation by fuel for every 15-minute settlement interval since 2007 (Fuel Mix "
                    "Report), MWh per interval, UTC with the published local day and interval.",
        parse=parse_fuel_mix,
        inputs=lambda f: f.suffix in {".xlsx", ".xls", ".zip"},
        select=latest_by(lambda f: f.meta.get("link_text") or f.url),
        key=("interval_start_utc", "fuel"),
        partition=("interval_start_utc", "MONTH"),
        cluster=("fuel",),
    ),
]
