"""Telling organizations from people in free-text name fields, so individuals' names can be dropped at parse
(docs/decisions.md: personal data stays in raw only).

There is no reliable marker in the Texas files: a name counts as an organization when it contains a legal
form or a business word from ``ORG_WORDS``; anything else is treated as a possible person. This errs on the
side of privacy: some real businesses without such a word (e.g. ``Buc-ee's``) are dropped too."""

from __future__ import annotations

import polars as pl

ORG_WORDS = (
    r"\b(LLC|L ?L ?C|INC|INCORPORATED|CORP|CORPORATION|CO|COMPANY|COMPANIES|LP|L ?P|LTD|LIMITED|LLP|PLLC|PC|PLC|"
    r"LC|GMBH|AG|SA|NV|BV|NA|N ?A|ASSOC|ASSOCIATES|ASSOCIATION|BANK|PARTNERS|PARTNERSHIP|GROUP|HOLDINGS?|"
    r"ENTERPRISES?|VENTURES?|SERVICES?|SOLUTIONS|INDUSTRIES|INDUSTRIAL|INTERNATIONAL|GLOBAL|SYSTEMS?|"
    r"TECHNOLOGY|TECHNOLOGIES|TECH|SOFTWARE|NETWORKS?|DATA|CLOUD|COMPUTE|DIGITAL|AUTO|AUTOMOTIVE|REPAIRS?|"
    r"SHOP|BODY|PAINT|COLLISION|CENTER|CENTRE|CONCRETE|PLATING|UNLIMITED|TRUCKS?|TRUCKING|CITY|COUNTY|"
    r"DISTRICT|SCHOOLS?|ISD|UNIVERSITY|COLLEGE|ACADEMY|CHURCH|MINISTRIES|STATE|TEXAS|USA|US|AMERICA|AMERICAN|"
    r"ENERGY|OIL|GAS|PIPELINE|MIDSTREAM|OPERATING|PRODUCTION|RESOURCES|PETROLEUM|CHEMICALS?|MANUFACTURING|"
    r"CONSTRUCTION|BUILDERS|HOMES?|FARMS?|RANCH|DAIRY|GIN|ELEVATOR|GROWERS|COOP|COOPERATIVE|MOTORS?|SALES|"
    r"SUPPLY|DEPT|DEPARTMENT|AUTHORITY|HOSPITAL|HEALTH|HEALTHCARE|MEDICAL|CLINIC|DENTAL|PHARMACY|CLEANERS|"
    r"FEED|MILLS?|PLANT|WORKS|PRODUCTS|MATERIALS|EQUIPMENT|STEEL|METALS?|PLASTICS|POLYMERS?|PACKAGING|"
    r"MEMBRANES|FOODS?|TRANSPORT|TRANSPORTATION|LOGISTICS|DISTRIBUTION|WAREHOUSE|STORAGE|CAPITAL|"
    r"INVESTMENTS?|EQUITIES|PROPERTY|PROPERTIES|REALTY|REAL ESTATE|DEVELOPMENT|DEVELOPERS|MANAGEMENT|"
    r"CONSULTING|FUND|FOUNDATION|INSTITUTE|TRUST|MARINE|AVIATION|AIRPORT|PORT|UTILITY|UTILITIES|WATER|"
    r"ELECTRIC|POWER|SOLAR|WIND|FORMER|PROJECT|APARTMENTS|LOFTS|VILLAGE|PLAZA|CROSSING|RETAIL|MALL|MARKET|"
    r"STORES?|MART|BOUTIQUE|OUTFITTERS|APPAREL|RESTAURANTS?|KITCHEN|CAFE|DELI|GRILL|BAR|BBQ|PIZZA|COFFEE|"
    r"BAKERY|BREWING|BREWERY|WINERY|DISTILLERY|HOTELS?|INN|SUITES|MOTEL|THEATRE|THEATER|BALLET|ARTS?|"
    r"MUSEUM|GALLERY|STUDIOS?|SALON|SPA|FITNESS|GYM|CLUB|LEAGUE|SOCIETY|ALLIANCE|COUNCIL|CHAMBER|EDC|"
    r"MEDIA|ENTERTAINMENT|RENTALS?|LEASING|FINANCIAL|INSURANCE|CREDIT|UNION|YOUTH|BOARD|COMMISSION)\b"
)


def is_org_name(expr: pl.Expr | str) -> pl.Expr:
    """True when the name contains an organization word; null names give false."""
    e = pl.col(expr) if isinstance(expr, str) else expr
    return (
        pl.coalesce(e.cast(pl.String), pl.lit(""))
        .str.to_uppercase()
        .str.replace_all(r"[.,&/()'\-]", " ")
        .str.contains(ORG_WORDS)
    )
