"""``basecast inventory``: what the lake holds, per raw source, rendered as Markdown."""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime, timezone

import polars as pl

from basecast_pipelines.common.etl_run import read_runs
from basecast_pipelines.common.manifest import MANIFEST_NAME
from basecast_pipelines.common.storage import Storage


@dataclass
class RawSourceSummary:
    source: str
    files: int
    bytes: int
    snapshots: list[str]
    extensions: dict[str, int]


def summarize_raw(storage: Storage) -> list[RawSourceSummary]:
    by_source: dict[str, RawSourceSummary] = {}
    for key in storage.list("raw/"):
        parts = key.split("/")
        if len(parts) < 4 or parts[-1] == MANIFEST_NAME:
            continue
        source = parts[1].removeprefix("source=")
        dt = parts[2].removeprefix("dt=")
        summary = by_source.setdefault(source, RawSourceSummary(source, 0, 0, [], {}))
        summary.files += 1
        summary.bytes += storage.size(key)
        if dt not in summary.snapshots:
            summary.snapshots.append(dt)
        ext = parts[-1].rsplit(".", 1)[-1].lower() if "." in parts[-1] else "(none)"
        summary.extensions[ext] = summary.extensions.get(ext, 0) + 1
    for summary in by_source.values():
        summary.snapshots.sort()
    return sorted(by_source.values(), key=lambda s: s.source)


def _last_runs(storage: Storage) -> dict[str, dict]:
    runs = read_runs(storage)
    if runs.is_empty():
        return {}
    last = runs.sort("started_at").group_by("source").last()
    return {row["source"]: row for row in last.iter_rows(named=True)}


def render_markdown(storage: Storage) -> str:
    summaries = summarize_raw(storage)
    last_runs = _last_runs(storage)
    total_bytes = sum(s.bytes for s in summaries)
    lines = [
        "# Data inventory",
        "",
        f"Generated by `basecast inventory` at {datetime.now(timezone.utc):%Y-%m-%d %H:%M} UTC. "
        "Raw layer only for now; typed Parquet datasets will be added as parsers land.",
        "",
        f"**Raw total:** {sum(s.files for s in summaries)} files, {total_bytes / 1e6:,.1f} MB.",
        "",
        "## Raw sources",
        "",
        "| Source id | Files | MB | Snapshots (dt) | dt range | Types | Last run | Status |",
        "|---|---:|---:|---:|---|---|---|---|",
    ]
    for s in summaries:
        run = last_runs.get(s.source)
        run_at = f"{run['started_at']:%Y-%m-%d %H:%M}" if run else ""
        status = run["status"] if run else ""
        types = ", ".join(f"{ext} {n}" for ext, n in sorted(s.extensions.items(), key=lambda x: -x[1]))
        dt_range = s.snapshots[0] if len(s.snapshots) == 1 else f"{s.snapshots[0]} → {s.snapshots[-1]}"
        lines.append(
            f"| `{s.source}` | {s.files} | {s.bytes / 1e6:,.1f} | {len(s.snapshots)} | {dt_range} | {types} "
            f"| {run_at} | {status} |"
        )
    failed = [r for r in last_runs.values() if r["status"] != "success"]
    if failed:
        lines += ["", "## Runs needing attention", ""]
        for r in failed:
            errors = [e for e in json.loads(r["events"]) if e.get("kind") == "error"]
            lines.append(f"- `{r['source']}` ({r['status']}): {r['error'] or ''} {len(errors)} item errors")
            lines += [f"  - {e.get('url')}: {e.get('error')}" for e in errors[:10]]
    return "\n".join(lines) + "\n"


def runs_table(storage: Storage) -> pl.DataFrame:
    return read_runs(storage).select(
        "source", "started_at", "status", "files", "files_skipped", "bytes", "duration_s", "error"
    )
